### PR TITLE
Add new landing page (WIP)

### PR DESCRIPTION
**Pull request by sauloantuness**
Hey @waltersf,

This is the new landing page I've been working on. It is still static (landing-page/index.html) 

I would like to know what do you think.

Once it will be OK, I will implement the right way in the project.

PS: Please don't merge this PR

### CODE REVIEW

**Comment by waltersf** [comment]
> landing-page/index.html

OK, Saulo, some comments:

- I think the "Services" part can be removed. The different micro services are just an internal aspect of the software, not a service that we provide to someone. Maybe in the future could be something link consulting or training, but not now. 
- The logo, at least in this page, could have the name Lemonade. And the color in gradient is suggesting more a peach than a lemon. 
- You need to add Atmosphere logo to the list of supporters. 

Thanks

**Comment by sauloantuness** [comment]
@waltersf do u think that is best a static html file or a vue component for the landing page?

**Comment by waltersf** [comment]
> @waltersf do u think that is best a static html file or a vue component for the landing page?

Static is better.

**Comment by sauloantuness** [comment]
I made some modifications:
- Changed the logo. I used as reference the colors of the emoji :lemon: used by the companies around the world [(link)](emojipedia.org/lemon/) (I don't know if this version is better than previous one :confused: )
- Remove the *Services* section
- Added Atmosphere logo
- I could not find a way to fit well the Lemonade text on the side of the logo for two reasons:
  - the logo and the menu are in the same height and
  -  the "Welcome Lemonade" is right below.
- Added the LandingPage as Vue component because could not figure out how to serve as static html. Please check if this is the better way to route the landing page.

**Comment by waltersf** [comment]
Will not merged because conflicts. Branch under reviewing.

**Pull request closed without merging**
